enyo.depends(
    "foss/jquery",
    "foss/underscore/underscore.js",
    "foss/backbone/backbone.js",
    "foss/backbone-relational/backbone-relational.js",
    "ext",
    "models",
    "controllers",
    "views"
);
