enyo.depends(
  "Core.js",
  "Store.js",
  "CollectionRowMixin.js",
  "SelectionSupportMixin.js",
  "CollectionRowControllerMixin.js",
  "CommonCollectionViewMixin.js",
  "CommonCollectionControllerMixin.js"
);
